# Generated by Django 3.0.8 on 2025-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20250815_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_active',
            field=models.BooleanField(default=True),
        ),
    ]
